### PR TITLE
Add factory to the project, fix tests in Wishlist controller and User model 

### LINKED ISSUE #57: Add factories to User spec and new test

### LINKED ISSUE #58: Fix tests in Wishlist controller

### PR DESCRIPTION
**Pull request by Kacper3331**
Close #58 and Close #57

### CODE REVIEW

File: spec/factories/wishlists.rb [hunk 1]
```diff
@@ -0,0 +1,12 @@
+FactoryGirl.define do
+  factory :wishlist do
+    name "Birthday"
+    description "Tom's 18th birtday"
```
Comment (student-tomasz) [inline spec/factories/wishlists.rb]: Typo in birthday. ;)

File: spec/factories/wishlists.rb [hunk 2]
```diff
@@ -0,0 +1,12 @@
+FactoryGirl.define do
+  factory :wishlist do
+    name "Birthday"
+    description "Tom's 18th birthday"
+  end
```
Comment (student-tomasz) [inline spec/factories/wishlists.rb]: Fill the association? https://github.com/thoughtbot/factory_girl/blob/master/GETTING_STARTED.md#associations

File: spec/models/user_spec.rb [hunk 3]
```diff
@@ -1,14 +1,21 @@
...
 RSpec.describe User do
-  let(:valid_user_params) { { email: "bob@example.org", password: "secret" } }
+  let(:valid_user_params) { attributes_for(:user) }
+  let(:valid_user) { create(:user) }
+  let(:valid_wishlist_params) { attributes_for(:wishlist) }
 
   it { is_expected.to have_many :wishlists }
 
   it "is valid with valid params" do
     expect(User.new(valid_user_params)).to be_valid
```
Comment (student-tomasz) [inline spec/models/user_spec.rb]: This should a factory call. All those `User.new(...)` calls later on should be factory calls `build(...)`.

File: spec/models/user_spec.rb [hunk 4]
```diff
@@ -1,14 +1,21 @@
 require "rails_helper"
 
 RSpec.describe User do
-  let(:valid_user_params) { { email: "bob@example.org", password: "secret" } }
+  let(:valid_user_params) { attributes_for(:user) }
+  let(:valid_user) { create(:user) }
+  let(:valid_wishlist_params) { attributes_for(:wishlist) }
```
Comment (student-tomasz) [inline spec/models/user_spec.rb]: I mean, the whole point of having factories is to get rid of `let`s like this one.

File: spec/controllers/wishlists_controller_spec.rb [hunk 5]
```diff
@@ -50,7 +48,7 @@
 
     context "with invalid parameters" do
       before do
-        request_post(invalid_parameters)
+        request_post(attributes_for(:invalid_wishlist))
```
Comment (student-tomasz) [inline spec/controllers/wishlists_controller_spec.rb]: 👍

File: spec/controllers/wishlists_controller_spec.rb [hunk 6]
```diff
@@ -63,7 +61,7 @@
 
       it "doesn't create new wishlist" do
         expect do
-          post :create, params: { wishlist: invalid_parameters }
+          post :create, params: { wishlist: attributes_for(:invalid_wishlist) }
         end.to_not change(Wishlist, :count)
```
Comment (student-tomasz) [inline spec/controllers/wishlists_controller_spec.rb:65]: While you're at it, this should fit in one line? (we've got 120 chars limit)

```
expect { post ... }.not_to change(Wishlist, :count)
```

File: spec/factories/wishlists.rb [hunk 7]
```diff
@@ -2,11 +2,13 @@
...
     name "Birthday"
     description "Tom's 18th birthday"
+    user
   end
 
   factory :invalid_wishlist, class: Wishlist do
     name ""
     description ""
     user_id nil
+    user
```
Comment (student-tomasz) [inline spec/factories/wishlists.rb]: Invalid is invalid. Shouldn't have a user? Either way, you should set `user_id` or use the association helper `user`, not both.

File: spec/models/user_spec.rb [hunk 8]
```diff
@@ -1,64 +1,59 @@
 require "rails_helper"
 
 RSpec.describe User do
-  let(:valid_user_params) { attributes_for(:user) }
-  let(:valid_user) { create(:user) }
-  let(:valid_wishlist_params) { attributes_for(:wishlist) }
-
```
Comment (student-tomasz) [inline spec/models/user_spec.rb:5]: 👍

File: spec/models/user_spec.rb [hunk 9]
```diff
@@ -1,64 +1,59 @@
...
 
       it "mangled" do
-        expect(User.new(valid_user_params.merge!(email: "bob-example@"))).not_to be_valid
+        expect(build(:user, email: "bob-example@")).not_to be_valid
       end
 
       it "non-unique" do
-        User.create(valid_user_params)
-        expect(User.new(valid_user_params.merge!(email: valid_user_params[:email]))).not_to be_valid
+        expect(build(:user, email: create(:user).email)).not_to be_valid
```
Comment (student-tomasz) [inline spec/models/user_spec.rb]: Does this really pass, with no other User in the DB?

File: spec/controllers/wishlists_controller_spec.rb (hunk 6 above)
Comment (Kacper3331) [inline spec/controllers/wishlists_controller_spec.rb:65]: I thought that the limit is 80 characters, okay I will change it.

File: spec/models/user_spec.rb (hunk 9 above)
Comment (Kacper3331) [inline spec/models/user_spec.rb]: It does, but there's a user when you want to associate email
`email: create(:user).email`
 it creates new user but it can't associate it because there's already user with this email. I don't know if my explanation is understandable.

Comment (student-tomasz) [inline spec/models/user_spec.rb]: Oh man. I didn't see the `create` in there. Definitely put it outside of the `expect` expression. Hides the intent of the test.

Comment (student-tomasz) [inline spec/models/user_spec.rb]: Here's why: https://robots.thoughtbot.com/four-phase-test

**Comment by student-tomasz** [comment]
I don't think we should define a factory for `invalid_wishlist`. We should generate an invalid one on a case-by-case basis, starting from the default, valid one. But that's something Oskar should comment on.

Otherwise 👍

**Comment by gotar** [comment]
It's a something very bad to create invalid factory, but I will create only valid ones and in let define invalid on base of valid one

**Comment by gotar** [comment]
but you can merge if you like, or fix and then merge

**Comment by gotar** [comment]
remember to squash
