### PR TITLE
Fix notice to not cover title on main page and fix errors in forms

### LINKED ISSUE #81: Fix notice to not cover title on main page and fix errors in forms

### PR DESCRIPTION
**Pull request by Kacper3331**
Close #81

### CODE REVIEW

File: app/helpers/devise_helper.rb [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+    html = <<-HTML
+    <div class="alert alert-danger">
+      <button type="button" class="close" data-dismiss="alert">x</button>
+      #{messages}
+    </div>
+    HTML
+
+    html.html_safe
+  end
+end
```
Comment (student-tomasz) [inline app/helpers/devise_helper.rb]: Get rid of this helper and use the notification plugin I'm using when displaying `flash` messages. Let's be consistent.

Comment (student-tomasz) [inline app/helpers/devise_helper.rb]: And the bang `!` is not needed. It doesn't throw any errors, does it?

File: app/assets/stylesheets/_devise_error_messages.scss [hunk 2]
```diff
@@ -0,0 +1,3 @@
+.message_width {
+  max-width: 500px;
+}
```
Comment (student-tomasz) [inline app/assets/stylesheets/_devise_error_messages.scss]: If you port the devise messages to the dynamic notification like flash messages this will be deleted. Either way, this width constraint should be left to the Bootstrap's grid system.

File: app/assets/stylesheets/_devise_error_messages.scss [hunk 3]
```diff
@@ -0,0 +1,3 @@
+.message_width {
```
Comment (smt116) [inline app/assets/stylesheets/_devise_error_messages.scss]: use `message-width` instead

File: app/assets/stylesheets/_devise_error_messages.scss [hunk 4]
```diff
@@ -0,0 +1,3 @@
...
+  max-width: 500px;
```
Comment (smt116) [inline app/assets/stylesheets/_devise_error_messages.scss]: why do you need a fixed width?

Comment (Kacper3331) [inline app/assets/stylesheets/_devise_error_messages.scss]: Because without it the message box is too wide and I wanted it to be smaller.

Comment (smt116) [inline app/assets/stylesheets/_devise_error_messages.scss]: Fixed width will not scale will user's screen resolution. If you have to make it shorter, maybe you could use proportion instead.

File: app/views/devise/registrations/new.html.erb [hunk 5]
```diff
@@ -1,33 +1,39 @@
...
+            <%= f.email_field :email, autofocus: true, class: "form-control input-width" %>
+          </div>
 
-      <div class="actions btn-in-sign-up-page">
-        <%= f.submit "Sign up", class: "btn btn-success" %>
-      </div>
+          <div class="field">
+            <%= f.label :password %>
+            <% if User::MINIMUM_PASSWORD_LENGTH %>
+              <em>(<%= User::MINIMUM_PASSWORD_LENGTH %> characters minimum)</em>
```
Comment (agalkiewicz) [inline app/views/devise/registrations/new.html.erb:20]: Are these brackets necessary?

File: app/views/devise/registrations/new.html.erb [hunk 6]
```diff
@@ -1,33 +1,39 @@
...
-  </div>
-  <%= form_for(resource, as: resource_name, url: registration_path(resource_name)) do |f| %>
-    <%= devise_error_messages! %>
-
-    <div class="content-in-block">
-      <div class="field">
-        <%= f.label :email %><br />
-        <%= f.email_field :email, autofocus: true, class: "form-control input-width" %>
+  <div class="row">
+    <div class="col-xs-4 col-xs-offset-4">
```
Comment (student-tomasz) [inline app/views/devise/registrations/new.html.erb:3]: 👍

File: app/views/shared/_flash_messages.html.erb [hunk 7]
```diff
@@ -6,7 +6,7 @@
     },
     offset: {
       x: 0,
-      y: 56
+      y: 55
```
Comment (student-tomasz) [inline app/views/shared/_flash_messages.html.erb:9]: That one pixel makes all the difference! 😉

File: app/views/devise/registrations/new.html.erb (hunk 5 above)
Comment (Kacper3331) [inline app/views/devise/registrations/new.html.erb:20]: With brackets -> **Password** (6 characters minimum) , without brackets -> **Password** 6 characters minimum

File: app/views/shared/_flash_messages.html.erb (hunk 7 above)
Comment (Kacper3331) [inline app/views/shared/_flash_messages.html.erb:9]: Oh, of course! 😉

**Comment by student-tomasz** [comment]
👍

**Comment by gotar** [comment]
ok you can merge
